### ISSUE TITLE
PHPStan 0.12 compatible

### ISSUE THREAD

**Issue by AJenbo** [phpstan/phpstan-mockery#12]
Are there any other needed changes then bumping the version for making this this extension compatible with the latest PHPStan develop version? Could I help out with the process some how?

https://github.com/phpstan/phpstan-mockery/blob/8f3f0dc0bbc8c413224459a25f89a2cef5924871/composer.json#L20

**Comment by ondrejmirtes** [comment]
Just did it: https://github.com/phpstan/phpstan-mockery/commit/52d0e2d81b2fcc3959a5bbfe99f337c93661667f
