### ISSUE TITLE
Passing an array as $methodNames argument in LegacyMockerInterface::shouldReceive() results in error

### ISSUE THREAD

**Issue by wimski** [phpstan/phpstan-mockery#23]
### Setup
`phpstan/phpstan-mockery` **0.12.7**
`phpstan/phpstan-phpunit` **0.12.16**

```neon
# phpstan.neon.dist
includes:
    - ./vendor/phpstan/phpstan-mockery/extension.neon
    - ./vendor/phpstan/phpstan-phpunit/extension.neon
```

#### No errors
Using the most basic `shouldReceive` syntax produces no PHPStan errors.
```php
/** @var MyClass|MockInterface */
$myMock = Mockery::mock(MyClass::class);
$myMock
    ->shouldReceive('someMethod')
    ->andReturn('resultString');
```

#### PHPStan error
Using the array notation for `shouldReceive` gives the following error:
```bash
Parameter #1 ...$methodNames of method Mockery\LegacyMockInterface::shouldReceive() expects string, array<string, string> given.
```

```php
/** @var MyClass|MockInterface */
$myMock = Mockery::mock(MyClass::class);
$myMock->shouldReceive([
    'someMethod' => 'resultString',
]);
```

http://docs.mockery.io/en/latest/reference/expectations.html

**Comment by ondrejmirtes** [comment]
Should be just a matter of updating the stubs: https://github.com/phpstan/phpstan-mockery/blob/master/stubs/MockInterface.stub

**Comment by wimski** [comment]
So that isn't supported in the current stub that comes with this package?

**Comment by ondrejmirtes** [comment]
Nope, `string[] ...$methodNames` means that the variadic argument accepts `string`.

**Comment by wimski** [comment]
Are you planning to update the stub to use `string[]|array` to match the signature of the LegacyMockInterface?

**Comment by ondrejmirtes** [comment]
@wimski You can send a PR by yourself :) I'd recommend `string[]|array<array<string, mixed>>`.

**Comment by wimski** [comment]
I will, but shouldn't it be `string|array<string, mixed> ...$methodNames`?

https://github.com/mockery/mockery/blob/14a510d1997d8e139a4414faea988d528ffc29ba/library/Mockery/LegacyMockInterface.php#L37

```php
// LegacyMockInterface

/**
 * Set expected method calls
 *
 * @param string|array ...$methodNames one or many methods that are expected to be called in this mock
 *
 * @return \Mockery\ExpectationInterface|\Mockery\Expectation|\Mockery\HigherOrderMessage
 */
public function shouldReceive(...$methodNames);
```

**Comment by ondrejmirtes** [comment]
Try and test it.

**Comment by wimski** [comment]
https://github.com/phpstan/phpstan-mockery/pull/24

**Comment by ondrejmirtes** [comment]
Fixed by https://github.com/phpstan/phpstan-mockery/pull/24.
