### ISSUE TITLE
Infer mock type when defined in setUp

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-mockery#27]
I'm having this test:
```php
use Mockery\MockInterface;

class TypedPropertyTest extends \PHPUnit\Framework\TestCase
{

	private MockInterface $fooMock;

	protected function setUp(): void
	{
		$this->fooMock = \Mockery::mock(Foo::class);
	}

	public function testAllows(): void
	{
		$bar = new Bar($this->fooMock);

		$this->fooMock
			->allows('doFoo')
			->with()
			->andReturn('foo');

		self::assertSame('foo', $bar->doFoo());
	}

}
```

But PHPStan reports issues:
```
 ------ ----------------------------------------------------------------------------------------------------------------------
  Line   tests/Mockery/TypedPropertyTest.php
 ------ ----------------------------------------------------------------------------------------------------------------------
  19     Parameter #1 $foo of class PHPStan\Mockery\Bar constructor expects PHPStan\Mockery\Foo, Mockery\MockInterface given.
  21     Call to an undefined method Mockery\ExpectationInterface|Mockery\HigherOrderMessage|Mockery\MockInterface::with().
 ------ ----------------------------------------------------------------------------------------------------------------------
```

The only way to solve this is by adding a PHPDoc:
```php
/** @var MockInterface|Foo */
private MockInterface $fooMock;
```

It would be great if it could read the `Foo` type from the `setUp` method and intersect that with `MockInterface` type.

@ondrejmirtes Is that possible? Do you maybe have an example that's similar? I'd like to create a PR to address it.

**Comment by ondrejmirtes** [comment]
Hi, this works exactly as it's supposed to. When PHP does not allow you to define the precise property type via native types, you need to add a PHPDoc.

The correct way to typehint this is MockInterface&Foo, see the differences between union types and intersection types: https://phpstan.org/blog/union-types-vs-intersection-types

There's a hardcoded exception so that MockInterface|Foo is also interpreted as an intersection type because that's what people mean when they write that.

I don't plan to infer the assigned type from the setUp() method, that's not what the extensions support.

**Comment by ruudk** [comment]
Thanks for the explanation. 

> There's a hardcoded exception so that MockInterface|Foo is also interpreted as an intersection type because that's what people mean when they write that.

Btw, I was aware of the intersection typing. Somehow people keep on adding the union types in our codebase. Would it be possible to make this configurable? So that you can only use intersect? (willing to create the PR if you agree).

**Comment by ondrejmirtes** [comment]
>Would it be possible to make this configurable?

Yes, it's easy.

1) Create a new bool parameter for this.
2) Remove the tag from this service definiton: https://github.com/phpstan/phpstan-mockery/blob/053bf9e3ffc4ff906e411636a43d440bace5b914/extension.neon#L60-L63
3) Create a new conditionalTags section like here: https://github.com/phpstan/phpstan-src/blob/6f7cadf96c7b55a0df21b51730e4b53ad13a7545/conf/config.level4.neon#L20-L30

**Comment by ruudk** [comment]
@ondrejmirtes Like this https://github.com/phpstan/phpstan-mockery/pull/28 :D ?
