### ISSUE TITLE
Incorrect doc blocks for shouldHaveReceived and shouldNotHaveReceived

### ISSUE THREAD

**Issue by dennis-koster** [phpstan/phpstan-mockery#57]
The doc blocks for the `shouldHaveReceived` and `shouldNotHaveReceived` methods in https://github.com/phpstan/phpstan-mockery/blob/245b17ccd00f04be3c6b9fc6645f63793b37b2ea/stubs/MockInterface.stub#L47 are incorrect.

These methods can also accept a `Closure` as the second argument, as you can see here: https://github.com/mockery/mockery/blob/master/library/Mockery/LegacyMockInterface.php#L87.

Currently, providing a closure as the second argument will trigger a PHPStan error.
```
 Parameter #2 $args of method Mockery\LegacyMockInterface::shouldNotHaveReceived() expects array<string>|null, Closure given.
 ```

**Comment by crazyball** [comment]
+1 any news of this fix ?

**Comment by fancyweb** [comment]
@dennis-koster Can you check https://github.com/phpstan/phpstan-mockery/pull/73 plz?
