### ISSUE TITLE
Require unit tests to call `Mockery::close()` or use `MockeryPHPUnitIntegration` trait

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-mockery#58]
When using Mockery in your PHPUnit tests, it's important to make sure you call `Mockery::close()` on `tearDown()`. Or use the `MockeryPHPUnitIntegration` trait for that.

This is often forgotten, and that leads to weird situations.

It would be great if the extension could detect this, and give an error instructing you what to do to solve it.

Some people might extend from a custom base class where this is done for them, for those this feature should be turned off, or configured so that it also supports a custom base class.

**Comment by ondrejmirtes** [comment]
Oh, I'm gonna give you some opinions :)

1) I'd argue that if it's so hard to use a mock framework right, I'd use a different framework. I have never been a fan of Mockery, I don't understand the syntax, PHPUnit mocks are much more natural for me. So this is just one more nail in its coffin.
2) I'd think this needs to be solved project-wide with a single line of code or configuration. Isn't there some kind of PHPUnit test listener to get rid of this problem correctly?
3) If you'd still want to solve this with PHPStan, I'd say that the best approach is a combination of 2 collectors and 1 rule.

About collectors: https://phpstan.org/developing-extensions/collectors

One collector would collect all the mock usages, another collector would collect all the `Mockery::close()` and then the final `CollectedDataNode` rule would evaluate whether all Mockery usages are covered by `close` calls.
